### ISSUE TITLE
Problem with WorkManager

### ISSUE THREAD

**Issue by JorisBodin** [hannesa2/paho.mqtt.android#230]
Since we use version 3.4.0-beta2 with WorkManager we have a job limit problem :

    java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2381)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:308)
        at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
        at androidx.work.impl.background.systemjob.SystemJobScheduler.scheduleInternal(SystemJobScheduler.java:187)
        at androidx.work.impl.background.systemjob.SystemJobScheduler.schedule(SystemJobScheduler.java:133)
        at androidx.work.impl.Schedulers.schedule(Schedulers.java:108)
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:226)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:110)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
    java.lang.IllegalStateException: JobScheduler 100 job limit exceeded.  We count 100 WorkManager jobs in JobScheduler; we have 3 tracked jobs in our DB; our Configuration limit is 20.
        at androidx.work.impl.background.systemjob.SystemJobScheduler.scheduleInternal(SystemJobScheduler.java:218)
        at androidx.work.impl.background.systemjob.SystemJobScheduler.schedule(SystemJobScheduler.java:133)
        at androidx.work.impl.Schedulers.schedule(Schedulers.java:108)
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:226)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:110)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
        
 Do you have any idea why it does that?

**Comment by JorisBodin** [comment]
I think it's from our implementation actually, I close. Thanks

**Comment by hannesa2** [comment]
I'm not sure. I guess it's the implementation here (too).
When you do

`class PingWorker(appContext: Context, workerParams: WorkerParameters, val comms: ClientComms?) : Worker(appContext, workerParams) {`

then this fails
<img width="668" alt="image" src="https://user-images.githubusercontent.com/3314607/137192015-eee3a742-0035-4197-a338-f73c11fc9bee.png">

As I understand, i should be

`class PingWorker(appContext: Context, workerParams: WorkerParameters) : Worker(appContext, workerParams) {`

**Comment by JorisBodin** [comment]
I test in 3.3.0 to be sure
I'll tell you tomorrow

**Comment by hannesa2** [comment]
Hi @JorisBodin did you made more tests and if yes, can you give me feedback ?
