### ISSUE TITLE
Fatal Exception: java.lang.Throwable: No Throwable given

### ISSUE THREAD

**Issue by ashik169** [hannesa2/paho.mqtt.android#246]
`Fatal Exception: java.lang.Throwable: No Throwable given
{.invocationContext=null, .errorMessage=not connected, .activityToken=504, .callbackAction=send, .clientHandle=tcp://m1-mqtt-broker.blowhorn.com:1883:driver_52598:net.blowhorn.driverapp, .callbackStatus=ERROR}
       at info.mqtt.android.service.MqttAndroidClient.simpleAction(MqttAndroidClient.kt:1000)
       at info.mqtt.android.service.MqttAndroidClient.sendAction(MqttAndroidClient.kt:1016)
       at info.mqtt.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.kt:893)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:254)
       at android.app.ActivityThread.main(ActivityThread.java:8243)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)`
       
       What issue is this?

**Comment by ashik169** [comment]
I have used version v3.3.1. Could you please explain?

**Comment by hannesa2** [comment]
What do you think ? https://github.com/hannesa2/paho.mqtt.android/pull/247

**Comment by hannesa2** [comment]
https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.3.2
