### ISSUE TITLE
[Crash] java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.

### ISSUE THREAD

**Issue by chihung93** [hannesa2/paho.mqtt.android#249]
Hello, I have received this crash on firebase. 

So How can I void this crash?

Version: com.github.hannesa2:paho.mqtt.android:3.3.1

org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5

```


Fatal Exception: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
       at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
       at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
       at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
       at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
       at 
android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:752)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(FrameworkSQLiteStatement.java:46)
       at info.mqtt.android.service.room.MqMessageDao_Impl.deleteClientHandle(MqMessageDao_Impl.java:229)
       at info.mqtt.android.service.MqttConnection.connect(MqttConnection.java:105)
       at info.mqtt.android.service.MqttService.connect(MqttService.java:289)
       at info.mqtt.android.service.MqttAndroidClient.doConnect(MqttAndroidClient.java:253)
       at info.mqtt.android.service.MqttAndroidClient.access$doConnect(MqttAndroidClient.java:39)
       at info.mqtt.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:1264)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1478)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1495)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:165)
       at android.app.ActivityThread.main(ActivityThread.java:6375)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

<img width="1354" alt="Screen Shot 2021-12-02 at 15 35 17" src="https://user-images.githubusercontent.com/5199109/144386351-72809fa2-60cb-4daa-9090-0996d814d9dc.png">

**Comment by hannesa2** [comment]
To be honest: I've no clue
It looks like a Room issue.

Interesting is what's the _state of the message queue_ At least the library does nothing with it

**Comment by hannesa2** [comment]
I see you solved it on your way https://github.com/eclipse/paho.mqtt.android/issues/465#issuecomment-988551522

**Comment by hannesa2** [comment]
Please use `3.3.5-beta2` it probably solves your issue.
https://github.com/hannesa2/paho.mqtt.android/issues/269#issuecomment-1014241499

**Comment by Vishal6ji2** [comment]
@hannesa2 did you solve this connection pool issue?

**Comment by hannesa2** [comment]
@Vishal6ji2 I never run into this. But it looks like a Room issue.
In short, I never solved this explicit, but probably an implicit update of Room did it. 

Maybe you give the recent version https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.5.1 a try ? 
Or even better, the current beta version https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.6.0-beta4 helps you to save battery and comes with most recent Room version.

I'm happy when I read the results. Positive and negative ones.
