### ISSUE TITLE
Crashes still happening on v3.3.2

### ISSUE THREAD

**Issue by ashik169** [hannesa2/paho.mqtt.android#256]
```
Fatal Exception: java.lang.Throwable: not connected
       at info.mqtt.android.service.MqttAndroidClient.simpleAction(MqttAndroidClient.kt:997)
       at info.mqtt.android.service.MqttAndroidClient.sendAction(MqttAndroidClient.kt:1019)
       at info.mqtt.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.kt:893)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:263)
       at android.app.ActivityThread.main(ActivityThread.java:8283)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

Please help me. Why is this happening?

**Comment by hannesa2** [comment]
You are not connected. Why ? You have to debug

**Comment by ashik169** [comment]
Thanks for the reply.

When was it not connected? did you mean while publishing?

**Comment by hannesa2** [comment]
You received here something 
<img width="558" alt="image" src="https://user-images.githubusercontent.com/3314607/145402802-1f745709-971a-4202-b265-15bae37cd9f2.png">

but as it looks like you are not connected. Sorry, diving deeper needs some debug from your side

**Comment by hannesa2** [comment]
I close it, but when it still exist, please reopen it again
