### ISSUE TITLE
SQLite Crash in v3.3.2

### ISSUE THREAD

**Issue by ashik169** [hannesa2/paho.mqtt.android#257]
`Fatal Exception: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
       at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
       at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
       at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
       at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:752)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(FrameworkSQLiteStatement.java:46)
       at info.mqtt.android.service.room.MqMessageDao_Impl.deleteClientHandle(MqMessageDao_Impl.java:229)
       at info.mqtt.android.service.MqttConnection.connect(MqttConnection.kt:105)
       at info.mqtt.android.service.MqttService.connect(MqttService.kt:289)
       at info.mqtt.android.service.MqttAndroidClient.doConnect(MqttAndroidClient.kt:253)
       at info.mqtt.android.service.MqttAndroidClient.access$doConnect(MqttAndroidClient.kt:39)
       at info.mqtt.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.kt:1267)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1461)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1489)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6393)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)`

Why is it happening? Please check this. Thanks

**Comment by hannesa2** [comment]
Even when you report it multiple times it becomes not better. 
* debug 
* solve
* create pull request

https://github.com/hannesa2/paho.mqtt.android/issues/250#issuecomment-990880779
