### ISSUE TITLE
 Cannot perform this operation because the connection pool has been closed.	

### ISSUE THREAD

**Issue by sisier** [hannesa2/paho.mqtt.android#272]
Thread Name: 'main'
Back traces starts.
java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1069)
	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:683)
	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:378)
	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:752)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(FrameworkSQLiteStatement.java:46)
	at info.mqtt.android.service.room.c.b(MqMessageDao_Impl.java:229)
	at info.mqtt.android.service.d.j(MqttConnection.kt:105)
	at info.mqtt.android.service.MqttService.j(MqttService.kt:289)
	at info.mqtt.android.service.MqttAndroidClient.K(MqttAndroidClient.kt:253)
	at info.mqtt.android.service.MqttAndroidClient.a(MqttAndroidClient.kt:39)
	at info.mqtt.android.service.MqttAndroidClient$b.onServiceConnected(MqttAndroidClient.kt:1259)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1771)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1803)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7085)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
Back traces ends.

Version used is  implementation 'com.github.hannesa2:paho.mqtt.android:3.3.5-beta2'   or 3.4.0  
Report this error often and then back off
Excuse me, how should solve. thank you

**Comment by sisier** [comment]
3.3.4 does not work either, and an error will be reported

**Comment by hannesa2** [comment]
https://github.com/hannesa2/paho.mqtt.android/issues/269#issuecomment-1017160900 an other guy reported to be solved. Anyway, I will try an other thing too

**Comment by hannesa2** [comment]
Please try `3.3.5` if the errors still exists, please reopen this
