### ISSUE TITLE
You need to use a Theme.AppCompat theme

### ISSUE THREAD

**Issue by Slake07** [hannesa2/paho.mqtt.android#307]
```
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
        at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
```

Getting this error while using the latest aar file of the 3.3.7 version.

**Comment by hannesa2** [comment]
Not sure what you are doing. Sample app is working properly and when you did a copy&paste from sample to your project, then please keep an eye on 
https://github.com/hannesa2/paho.mqtt.android/blob/master/extendedSample/src/main/res/values/styles.xml#L4-L14 
or 
https://github.com/hannesa2/paho.mqtt.android/blob/master/basicSample/src/main/res/values/styles.xml#L4-L14

**Comment by Slake07** [comment]
I am using **Theme.MaterialComponents.Light.NoActionBar** in style. As it is the latest one and my app is compatible with that only.

**Comment by hannesa2** [comment]
I'm not able to analyze with given info from fare away not seeing **all** code

**Comment by Slake07** [comment]
As per issue, I have to use Theme.AppCompat theme in my application. But it's already live and it supports material theme so I can't change to that theme. Currently I am using Theme.MaterialComponents.Light.NoActionBar theme.

**Comment by hannesa2** [comment]
> I'm not able to analyze with given info from fare away not seeing **all** code

Which activity do you open to see this error ?

**Comment by Slake07** [comment]
It crashed whenever I open my app. So I think while initializing MQTT object, that time crash happens. So the first activity is splash screen of my app.

**Comment by hannesa2** [comment]
How does you `implements` looks like ?
But this conversation makes no sense, as long as I don't see the complete code which points to the issue

**Comment by Slake07** [comment]
I added my mqtt class above.

**Comment by hannesa2** [comment]
I remove one [unused styling](https://github.com/hannesa2/paho.mqtt.android/pull/308) item here
https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.3.8 maybe it causes this.
If it still exists, please point me to the causing line. I don't find any

**Comment by hannesa2** [comment]
> I added my mqtt class above.

Sorry this makes me too much afford. I'll look into something when I can clone and run it, anything else make s me too much afford. I do not construct a showcase. -sorry-

**Comment by hannesa2** [comment]
> implementation files('libs/mqtt.aar')

Why not using jitpack ? Doing like you did is always a kind of error source on not knowing exactly what aar it is

**Comment by Slake07** [comment]
First I tried jitpack only but Gradle didn't find such dependency I had to use such a way.

**Comment by Slake07** [comment]
Now, getting different error while using 3.3.8 aar:

`java.lang.NoClassDefFoundError: Failed resolution of: Ltimber/log/Timber;
        at info.mqtt.android.service.MqttConnection.connect(MqttConnection.kt:95)
        at info.mqtt.android.service.MqttService.connect(MqttService.kt:289)
        at info.mqtt.android.service.MqttAndroidClient.doConnect(MqttAndroidClient.kt:253)
        at info.mqtt.android.service.MqttAndroidClient.access$doConnect(MqttAndroidClient.kt:39)
        at info.mqtt.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.kt:1267)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1967)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1999)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8056)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)`

**Comment by hannesa2** [comment]
> First I tried jitpack only but Gradle didn't find such dependency I had to use such a way.

This is your first failure. Fix it !

**Comment by Slake07** [comment]
Solved both issues. Thanks(Y)

**Comment by Slake07** [comment]
I am still not able to get a response from MQTT in android 12. Do you know anything about that?
