### ISSUE TITLE
StrictMode policy DiskWrite/ReadViolation

### ISSUE THREAD

**Issue by tsm** [hannesa2/paho.mqtt.android#312]
Hi, after turning on StrictMode I encounter DiskWriteViolation and DiskReadViolation when a message arrives. Version 3.3.8 on Android 12 (many devices), MqttAndroidClient with setForegroundService. Probably write/read to disk (to the database) should be done on the work thread.

Code in Application.onCraate():
```
StrictMode.setThreadPolicy(
                StrictMode.ThreadPolicy.Builder()
                    .detectDiskReads()
                    .detectDiskWrites()
                    .detectNetwork()
                    .penaltyLog()
                    .build()
            )
```

Logs:
```
D/StrictMode: StrictMode policy violation; ~duration=15 ms: android.os.strictmode.DiskWriteViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1615)
        at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1201)
        at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:706)
        at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:321)
        at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
        at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:572)
        at android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive(SQLiteDatabase.java:506)
        at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransactionNonExclusive(FrameworkSQLiteDatabase.java:78)
        at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:570)
        at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:555)
        at info.mqtt.android.service.room.MqMessageDao_Impl.deleteId(MqMessageDao_Impl.java:206)
        at info.mqtt.android.service.room.MqMessageDatabase.discardArrived(MqMessageDatabase.kt:37)
        at info.mqtt.android.service.MqttService.acknowledgeMessageArrival(MqttService.kt:491)
        at info.mqtt.android.service.MqttAndroidClient.messageArrivedAction(MqttAndroidClient.kt:1066)
        at info.mqtt.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.kt:887)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
```
StrictMode policy violation; ~duration=14 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
        at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1199)
        at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:706)
        at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
        at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:403)
        at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:589)
        at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(FrameworkSQLiteDatabase.java:94)
        at androidx.room.RoomDatabase.internalEndTransaction(RoomDatabase.java:594)
        at androidx.room.RoomDatabase.endTransaction(RoomDatabase.java:584)
        at info.mqtt.android.service.room.MqMessageDao_Impl.deleteId(MqMessageDao_Impl.java:212)
        at info.mqtt.android.service.room.MqMessageDatabase.discardArrived(MqMessageDatabase.kt:37)
        at info.mqtt.android.service.MqttService.acknowledgeMessageArrival(MqttService.kt:491)
        at info.mqtt.android.service.MqttAndroidClient.messageArrivedAction(MqttAndroidClient.kt:1066)
        at info.mqtt.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.kt:887)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by tsm** [comment]
Of course this is not urgent at all. Thank you for running and making this open source project available. Just thought I'd let you know that it's happening.

Yes, a dozen ms is not much, but when mqtt is used heavily it can add up to have a small impact on application speed.

**Comment by hannesa2** [comment]
@tsm You could help me and try to run strict mode version on your side. At least on my side, it works properly now

`implementation 'com.github.hannesa2:paho.mqtt.android:StrictMode-3.4.0-g81265c0-10'`

**Comment by tsm** [comment]
Gradle was unable to resolve **StrictMode-3.4.0-g81265c0-10**, while **StrictMode-SNAPSHOT** is working for me. Hope it's the same.

I started the application and when running, I actually don't get StrictMode logs as often as it was before. **This is a great improvement!**

However, I do not know if it is a matter of a new configuration (+ run on Android 12 device):
```
StrictMode.ThreadPolicy.Builder().detectAll()
StrictMode.VmPolicy.Builder().detectAll()
```

but Strict Mode logs still show up in 2 situations:


1) When I manually turn off and on Internet connection eg. Wifi (perhaps saving to/loading from the cache?):
```
2022-07-19 14:41:23.322 D: StrictMode policy violation; ~duration=2 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:268)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7725)
        at libcore.io.IoBridge.open(IoBridge.java:561)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
        at org.eclipse.paho.client.mqttv3.internal.FileLock.<init>(FileLock.java:49)
        at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.open(MqttDefaultFilePersistence.java:120)
        at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(ConnectActionListener.java:174)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:766)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.attemptReconnect(MqttAsyncClient.java:1428)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1410)
        at info.mqtt.android.service.MqttConnection.reconnect(MqttConnection.kt:746)
        at info.mqtt.android.service.MqttService.reconnect(MqttService.kt:304)
        at info.mqtt.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.kt:662)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1679)
        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2022-07-19 14:41:23.322 D: StrictMode policy violation; ~duration=2 ms: android.os.strictmode.DiskWriteViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1615)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:271)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7725)
        at libcore.io.IoBridge.open(IoBridge.java:561)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
        at org.eclipse.paho.client.mqttv3.internal.FileLock.<init>(FileLock.java:49)
        at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.open(MqttDefaultFilePersistence.java:120)
        at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(ConnectActionListener.java:174)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:766)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.attemptReconnect(MqttAsyncClient.java:1428)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1410)
        at info.mqtt.android.service.MqttConnection.reconnect(MqttConnection.kt:746)
        at info.mqtt.android.service.MqttService.reconnect(MqttService.kt:304)
        at info.mqtt.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.kt:662)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1679)
        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

2) at the beginning of connection (it is not that important):
```
StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setTrafficStatsTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2251)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:55)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:403)
        at libcore.io.ForwardingOs.socket(ForwardingOs.java:827)
        at libcore.io.IoBridge.socket(IoBridge.java:843)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:128)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
        at java.net.Socket.createImpl(Socket.java:489)
        at java.net.Socket.connect(Socket.java:619)
        at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:156)
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:74)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:132)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
        at java.lang.Thread.run(Thread.java:920)
```

In any case, thank you for addressing the issue and I think it is going in the right direction

**Comment by hannesa2** [comment]
> Gradle was unable to resolve **StrictMode-3.4.0-g81265c0-10**

Hmm, the build is there 
<img width="626" alt="image" src="https://user-images.githubusercontent.com/3314607/179755360-64098fff-70c6-4f92-bf83-7cea6bf57d88.png">

**Comment by hannesa2** [comment]
`info.mqtt.android.service.MqttConnection.reconnect(MqttConnection.kt:746)`

I fixed this (hopefully), please test it again with.
`implementation 'com.github.hannesa2:paho.mqtt.android:6caf9b11'`

**Comment by hannesa2** [comment]
I (hopefully) fixed 1. and concerning 2. I did a blind shot. I hope aef3f3cd30 helps

Please test it again with
`implementation 'com.github.hannesa2:paho.mqtt.android:aef3f3cd30'`

**Comment by tsm** [comment]
1) No crash on **aef3f3cd30**, no StrictMode read/write disk logs, successfully reconnect (wifi off and on) and mqtt messages start to be exchanged again. Nice!

When trying to reconnect, normal errors appear in the logs (but it does not crash the application):
```
2022-07-20 10:24:00.317 I/MqttConnection: Requesting Automatic reconnect using New Java AC
2022-07-20 10:24:00.320 E/MqttConnection$reconnect: Exception occurred attempting to reconnect: Connect already in progress
    Connect already in progress (32110)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1399)
        at info.mqtt.android.service.MqttConnection$reconnect$1.invokeSuspend(MqttConnection.kt:747)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-07-20 10:24:00.606 I/MqttConnection: Client is not connected, so not sending message
```

2) The UntaggedSocketViolation logs are still displayed. Maybe it's something in the eclipse code, so you can probably remove setThreadStatsTag from the AlarmPingSender (doesn't help).
