### ISSUE TITLE
3.6.0-beta1

### ISSUE THREAD

**Issue by lhj1079947827** [hannesa2/paho.mqtt.android#355]
E/SQLiteDatabase: Failed to open database '/data/user/0/com.demo/no_backup/androidx.work.workdb'.
    android.database.sqlite.SQLiteException: Failed to change locale for db '/data/user/0/com.demo/no_backup/androidx.work.workdb' to 'zh_CN'.
        at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:394)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:219)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:493)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:200)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:192)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:864)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:849)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:724)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:295)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:238)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:151)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:112)
        at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:706)
        at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:483)
        at androidx.work.impl.model.SystemIdInfoDao_Impl.getWorkSpecIds(SystemIdInfoDao_Impl.java:120)
        at androidx.work.impl.background.systemjob.SystemJobScheduler.reconcileJobs(SystemJobScheduler.java:298)
        at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:249)
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:215)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:110)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForString(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:642)
        at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:375)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:219) 
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194) 
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:493) 
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:200) 
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:192) 
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:864) 
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:849) 
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:724) 
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714) 
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:295) 
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:238) 
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:151) 
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:112) 
        at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:706) 
        at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:483) 
        at androidx.work.impl.model.SystemIdInfoDao_Impl.getWorkSpecIds(SystemIdInfoDao_Impl.java:120) 
        at androidx.work.impl.background.systemjob.SystemJobScheduler.reconcileJobs(SystemJobScheduler.java:298) 
        at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:249) 
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:215) 
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:110) 
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by hannesa2** [comment]
> SQLiteDatabaseCorruptException: database disk image is malformed (code 11)

Looks like a general error on your device

**Comment by lhj1079947827** [comment]
This problem should not arise

**Comment by hannesa2** [comment]
please reopen if you still have such issues
