### ISSUE TITLE
android instrumentation test : Bad notification for startForeground

### ISSUE THREAD

**Issue by SalauddinGaziMeldcx** [hannesa2/paho.mqtt.android#435]
```
android.app.RemoteServiceException: Bad notification for startForeground
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```
This error occurs if we set the set Foreground Service in the android instrumentation test : 

```
 val client = MqttAndroidClient(context, uri, clientId).apply {
                if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O && FOREGROUND)
                    setForegroundService(foregroundNotification, 77)
            }

```

**Comment by hannesa2** [comment]
I have some Espresso tests as well. Please can you make a pull request to show me, how to reproduce it ?

**Comment by hannesa2** [comment]
Without running sample I close it. You can reopen it if you still need it.
Btw, version 4.x is released, this doesn't use a foreground service anymore
