### ISSUE TITLE
java.lang.IllegalStateException: Maximum limit of concurrent alarms 500 reached for uid: u0a491

### ISSUE THREAD

**Issue by mintheinwin** [hannesa2/paho.mqtt.android#466]
When I disconnect wifi and reconnect wifi and connect to Mqtt and then publish message app have going to crashed. Error have shown at the follow. How to solve this issues? Please help...
Android Device: Red Noted 10S
I use these library gradle version. 
implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
implementation 'com.github.hannesa2:paho.mqtt.android:3.3.5'

java.lang.IllegalStateException: Maximum limit of concurrent alarms 500 reached for uid: u0a491, callingPackage: com.mtwin.androidmqttbroker
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3019)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:344)
        at android.app.AlarmManager.setImpl(AlarmManager.java:982)
        at android.app.AlarmManager.setImpl(AlarmManager.java:942)
        at android.app.AlarmManager.setExact(AlarmManager.java:740)
        at info.mqtt.android.service.ping.AlarmPingSender.schedule(AlarmPingSender.kt:92)
        at info.mqtt.android.service.ping.AlarmPingSender.start(AlarmPingSender.kt:60)
        at org.eclipse.paho.client.mqttv3.internal.ClientState.connected(ClientState.java:1214)
        at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:1050)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:151)
        at java.lang.Thread.run(Thread.java:1012)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.alarm.AlarmManagerService.setImpl(AlarmManagerService.java:2349)
        at com.android.server.alarm.AlarmManagerService$5.set(AlarmManagerService.java:2989)
        at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:198)
        at android.os.Binder.execTransactInternal(Binder.java:1285)
        at android.os.Binder.execTransact(Binder.java:1249)

**Comment by hannesa2** [comment]
Please try more recent [3.5.2](https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.5.2)

or [3.6.0-beta7](https://github.com/hannesa2/paho.mqtt.android/releases/tag/3.6.0-beta7) which helps to save energy

**Comment by mintheinwin** [comment]
Hi @hannesa2 Thanks for Reply. When I try new gradle version (3.6.0-beta7 and up to 4.0-beta2). I got new issues.
These issues are I got when I try to connect mqtt with disconnect wifi or 3G mobile. 
Action: If click to connect mqtt one more time with disconnect wifi or 3G mobile connection.

Error Log: 
android.app.RemoteServiceException$CannotDeliverBroadcastException: can't deliver broadcast
        at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2082)
        at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2344)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:211)
        at android.os.Looper.loop(Looper.java:300)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
