### ISSUE TITLE
PingWorker not work

### ISSUE THREAD

**Issue by shenyunhuan** [hannesa2/paho.mqtt.android#502]
Work [ id=42e1814b-15be-45aa-9fba-293602b236b0, tags={ info.mqtt.android.service.ping.PingWorker } ] was cancelled
                 java.util.concurrent.CancellationException: Task was cancelled.
                 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
                 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
                 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
                 	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                 	at java.lang.Thread.run(Thread.java:1012)

**Comment by rainfoam** [comment]
@hannesa2 Changing the keepAlive time to a very short time such as 10 seconds will reproduce this problem very well. My solution is to modify "ExistingWorkPolicy. REPLACE" as "ExistingWorkPolicy. KEEP". I wonder if this is a good solution? Thanks!

**Comment by rainfoam** [comment]
log:

2023-09-19 10:54:24.775 16014-16315 ACLog                    D  MQTT Ping AlarmPingSender start
2023-09-19 10:54:24.775 16014-16315 ACLog                    D  MQTT Ping AlarmPingSender Schedule next alarm at 1695092074775
2023-09-19 10:54:34.791 16014-16244 ACLog                    D  MQTT Ping PingWorker  Sending at: 1695092074791
2023-09-19 10:54:34.791 16014-16244 ACLog                    D  MQTT Ping AlarmPingSender Schedule next alarm at 1695092084791
2023-09-19 10:54:34.810 16014-16317 ACLog                    D  MQTT Ping PingWorker Success.
2023-09-19 10:54:34.821 16014-16076 WM-WorkerWrapper         I  Work [ id=cfb5d49f-8685-45f9-acbe-c0a042abfea3, tags={ ac.cloud.common.mqtt.ping.PingWorker } ] was cancelled
                                                                java.util.concurrent.CancellationException: Task was cancelled.
                                                                	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
                                                                	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
                                                                	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                                                                	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:311)
                                                                	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
                                                                	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                	at java.lang.Thread.run(Thread.java:1012)
2023-09-19 10:54:44.806 16014-16244 ACLog                    D  MQTT Ping PingWorker  Sending at: 1695092084806
2023-09-19 10:54:44.807 16014-16244 ACLog                    D  MQTT Ping AlarmPingSender Schedule next alarm at 1695092094807
2023-09-19 10:54:44.833 16014-16317 ACLog                    D  MQTT Ping PingWorker Success.
2023-09-19 10:54:44.846 16014-16076 WM-WorkerWrapper         I  Work [ id=8542efe3-663a-40a2-872b-df4529f748a4, tags={ ac.cloud.common.mqtt.ping.PingWorker } ] was cancelled
                                                                java.util.concurrent.CancellationException: Task was cancelled.
                                                                	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
                                                                	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
                                                                	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                                                                	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:311)
                                                                	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
                                                                	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                	at java.lang.Thread.run(Thread.java:1012)

**Comment by hannesa2** [comment]
Please can you demonstrate your change as a pull request ?

Here you have something to read https://issuetracker.google.com/issues/122578012?pli=1

eg.

> Status: Won't Fix (Intended Behavior)
> This is expected. You are calling: enqueueUniquePeriodicWork() with an ExistingPeriodicWorkPolicy.REPLACE. This will cancel running work, and kick off new instances of all Workers.
> [https://github.com/rubensousa/WorkManagerKitkatBug/blob/master/app/src/main/java/com/github/rubensousa/workkitkatbug/MainActivity.kt#L24](https://www.google.com/url?q=https://github.com/rubensousa/WorkManagerKitkatBug/blob/master/app/src/main/java/com/github/rubensousa/workkitkatbug/MainActivity.kt%23L24&sa=D&source=buganizer&usg=AOvVaw36ypXL8BbYlAiuT2EOz3mk)

I'm not sure if it's just a "(Intended Behavior"

**Comment by wwqbus** [comment]
since 4.1 i have noticed this as well but it makes it so that the connection has more losses then i had with 3.5.1

2023-09-29 09:06:22.148 28065-28106 WM-WorkerWrapper        com.qbus.ubie                        I  Work [ id=3e113b43-0d60-4a35-8d38-2e20860e8a54, tags={ info.mqtt.android.service.ping.PingWorker } ] was cancelled
                                                                                                    java.util.concurrent.CancellationException: Task was cancelled.
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                                                                                                    	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
                                                                                                    	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2023-09-29 09:06:40.685 28065-28079 com.qbus.ubie           com.qbus.ubie                        I  Background concurrent copying GC freed 80343(6260KB) AllocSpace objects, 0(0B) LOS objects, 46% free, 6950KB/12MB, paused 159us total 113.095ms
2023-09-29 09:06:48.205 28065-28662 ContentValues           com.qbus.ubie                        I  reveived packet: UBIE?
2023-09-29 09:06:48.491 28065-28662 ContentValues           com.qbus.ubie                        I  reveived packet: UBIE:UB10000005EE:192.168.75.120:255.255.255.0:192.168.75.1:192.168.75.3:3000
2023-09-29 09:06:48.808 28065-28662 ContentValues           com.qbus.ubie                        I  reveived packet: UBIE:PROTO0000009:192.168.75.110:255.255.255.0:192.168.75.1:192.168.75.3:3000
2023-09-29 09:06:57.704 28065-28079 com.qbus.ubie           com.qbus.ubie                        I  Background young concurrent copying GC freed 72797(5959KB) AllocSpace objects, 0(0B) LOS objects, 45% free, 7161KB/12MB, paused 5.371ms total 52.301ms
2023-09-29 09:07:18.205 28065-28662 ContentValues           com.qbus.ubie                        I  reveived packet: UBIE?
2023-09-29 09:07:18.497 28065-28662 ContentValues           com.qbus.ubie                        I  reveived packet: UBIE:UB10000005EE:192.168.75.120:255.255.255.0:192.168.75.1:192.168.75.3:3000
2023-09-29 09:07:18.802 28065-28662 ContentValues           com.qbus.ubie                        I  reveived packet: UBIE:PROTO0000009:192.168.75.110:255.255.255.0:192.168.75.1:192.168.75.3:3000
2023-09-29 09:07:22.796 28065-20168 mqtt                    com.qbus.ubie                        E  connection lost cloud
                                                                                                    Connection lost (32109) - java.io.EOFException
                                                                                                    	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    Caused by: java.io.EOFException
                                                                                                    	at java.io.DataInputStream.readByte(DataInputStream.java:270)
                                                                                                    	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
                                                                                                    	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
                                                                                                    	at java.lang.Thread.run(Thread.java:923) 
2023-09-29 09:07:22.964 28065-28665 WM-Processor            com.qbus.ubie                        W  Didn't find WorkSpec for id WorkGenerationalId(workSpecId=263da75c-44d6-4b8a-b408-5a08fa7a3557, generation=0)
2023-09-29 09:07:23.802 28065-20307 System.out              com.qbus.ubie                        I  [socket]:check permission begin!
2023-09-29 09:07:24.301 28065-20014 mqtt                    com.qbus.ubie                        I  connected to mqtt, was reconnect: true

**Comment by uiTravis** [comment]
+1

**Comment by SM2A** [comment]
I was testing the latest version and still facing this issue. As a sample I just ran `basicSample` and waited for a while. In the logcat you can constantly see mentioned errors.

**Comment by GCIotron** [comment]
Hello, I'm having the same issue since version 4.0

**Comment by don-pironet-hatch** [comment]
Hi, we are having the same issue on version 4.2.4 on Samsung Galaxy tab with Android 11 and on a Pixel 6A with Android 14.

**Comment by contigo** [comment]
hello 
android 12(LG V50), 14 (Galaxy Z Fold3 5G) and lib 3.6.4 same issue 
any solution?

**Comment by hannesa2** [comment]
> same issue

This is too easy. 
1. which version do you use ?
2. How does *your* issue looks like ?

**Comment by contigo** [comment]
> > same issue
> 
> This is too easy.
> 
> 1. which version do you use ?
-  I use version 3.6.4
> 2. How does _your_ issue looks like ?
- I checked that the operation was canceled in the background task inspector of the app inspector in Android Studio. It is not 100% an error.

**Comment by hannesa2** [comment]
Cancellation does not mean that it's automatic an error. It's a cancel !

Btw, please consider to move to 
https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.2.4
I personally would use 
https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.3.beta3

**Comment by craigt543nz** [comment]
I have the same issue on multiple test devices (new and old). I'm currently testing on a Galaxy S10, Android version 12 and MQTT version 4.2.4. Error message below. Any progress with this issue?

BTW, great work supporting this library.

12:39:07.323  I  Work [ id=8beff531-e410-4953-8d28-d189953300fc, tags={ info.mqtt.android.service.ping.PingWorker } ] was cancelled
                 java.util.concurrent.CancellationException: Task was cancelled.
                 	at T0.g.f(Unknown Source:32)
                 	at T0.g.get(SourceFile:86)
                 	at l.k.f(Unknown Source:9)

**Comment by chrjsorg** [comment]
The issue is still present in 4.3.beta5. Without any interaction. Just opened a connection and did a subscribe.

```
2024-11-29 07:48:54.369 10458-10458 WM-WorkerWrapper         D  Starting work for info.mqtt.android.service.ping.PingWorker
2024-11-29 07:48:54.373 10458-10529 PingWorker               D  Sending Ping at: 2024-11-29 07:48:54Z
2024-11-29 07:48:54.376 10458-10529 AlarmPingSender          D  Schedule next alarm at 2024-11-29 07:49:04Z
2024-11-29 07:48:54.387 10458-10542 WM-Processor             D  Processor cancelling 40669dfb-b0cf-4f14-8c9c-2aeadc2ccb4e
2024-11-29 07:48:54.393 10458-10542 WM-Processor             D  WorkerWrapper interrupted for 40669dfb-b0cf-4f14-8c9c-2aeadc2ccb4e
2024-11-29 07:48:54.400 10458-10542 WM-GreedyScheduler       D  Cancelling work ID 40669dfb-b0cf-4f14-8c9c-2aeadc2ccb4e
2024-11-29 07:48:54.420 10458-10542 WM-SystemJobScheduler    D  Scheduling work ID 792c6da1-ab12-4ae0-adae-c0f6f25b71ebJob ID 175
2024-11-29 07:48:54.427 10458-10542 WM-WorkerWrapper         I  Work [ id=40669dfb-b0cf-4f14-8c9c-2aeadc2ccb4e, tags={ info.mqtt.android.service.ping.PingWorker } ] was cancelled (Ask Gemini)
                                                                androidx.work.impl.WorkerStoppedException
                                                                	at androidx.work.impl.WorkerWrapper.interrupt(WorkerWrapper.kt:348)
                                                                	at androidx.work.impl.Processor.interrupt(Processor.java:439)
                                                                	at androidx.work.impl.Processor.stopAndCancelWork(Processor.java:280)
                                                                	at androidx.work.impl.utils.CancelWorkRunnable.cancel(CancelWorkRunnable.kt:33)
                                                                	at androidx.work.impl.utils.CancelWorkRunnable.forNameInline$lambda$0(CancelWorkRunnable.kt:127)
                                                                	at androidx.work.impl.utils.CancelWorkRunnable.$r8$lambda$gmz-7SyxTGDd6CwHjvOsJ11-hcc(Unknown Source:0)
                                                                	at androidx.work.impl.utils.CancelWorkRunnable$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                	at androidx.room.RoomDatabase.runInTransaction(RoomDatabase.kt:585)
                                                                	at androidx.work.impl.utils.CancelWorkRunnable.forNameInline(CancelWorkRunnable.kt:123)
                                                                	at androidx.work.impl.utils.EnqueueRunnable.enqueueWorkWithPrerequisites(EnqueueRunnable.java:249)
                                                                	at androidx.work.impl.utils.EnqueueRunnable.enqueueContinuation(EnqueueRunnable.java:136)
                                                                	at androidx.work.impl.utils.EnqueueRunnable.processContinuation(EnqueueRunnable.java:129)
                                                                	at androidx.work.impl.utils.EnqueueRunnable.addToDatabase(EnqueueRunnable.java:93)
                                                                	at androidx.work.impl.utils.EnqueueRunnable.enqueue(EnqueueRunnable.java:74)
                                                                	at androidx.work.impl.WorkContinuationImpl.lambda$enqueue$0$androidx-work-impl-WorkContinuationImpl(WorkContinuationImpl.java:201)
                                                                	at androidx.work.impl.WorkContinuationImpl$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
                                                                	at androidx.work.OperationKt.launchOperation$lambda$2$lambda$1(Operation.kt:50)
                                                                	at androidx.work.OperationKt.$r8$lambda$XKAkIiEN7OgIvwuLUZRQpJhjmyE(Unknown Source:0)
                                                                	at androidx.work.OperationKt$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
                                                                	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                                                	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                	at java.lang.Thread.run(Thread.java:1012)
2024-11-29 07:48:54.429 10458-10542 WM-WorkerWrapper         D  Status for 40669dfb-b0cf-4f14-8c9c-2aeadc2ccb4e is null ; not doing any work
2024-11-29 07:48:54.430 10458-10542 WM-StopWorkRunnable      D  StopWorkRunnable for 40669dfb-b0cf-4f14-8c9c-2aeadc2ccb4e; Processor.stopWork = false
2024-11-29 07:48:54.431 10458-10458 WM-Processor             D  Processor 40669dfb-b0cf-4f14-8c9c-2aeadc2ccb4e executed; reschedule = false
2024-11-29 07:48:54.434 10458-10550 WM-GreedyScheduler       D  Cancelling work ID 40669dfb-b0cf-4f14-8c9c-2aeadc2ccb4e
2024-11-29 07:48:54.553 10458-10570 PingWorker$doWork        D  Success null
```

I cannot currently see that it is causing any problems in use. It just floods the logs.

Cheers & thanks for this fork.

**Comment by chlim77** [comment]
I have the same issue.
I'm currently testing on android device with Android version 14 and MQTT version 4.2.4. 

I used to leave the device for hours to check the mqtt connection while it was in sleep mode.
But every time, GC was running and it didn't stop.

I wonder if there is a way to turn off the workmanager operation.

Error message below.
Thanks.

2025-02-20 14:55:44.602  5552-5779  WM-WorkerWrapper	I  Work [ id=d2da2d90-423c-4242-914e-d35e4fd163a4, tags={ info.mqtt.android.service.ping.PingWorker } ] was cancelled
                                                                               java.util.concurrent.CancellationException: Task was cancelled.
                                                                               at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1183)
                                                                               at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:513)
                                                                               at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
                                                                               at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
                                                                               at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                               at java.lang.Thread.run(Thread.java:1012)

2025-02-20 14:55:52.660  5552-5603  xxx.xxx.xxx             I  Explicit concurrent mark compact GC freed 2499(472KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5334KB/10MB, paused 365us,2.616ms total 35.362ms
2025-02-20 14:55:52.773  5552-5603  LeakCanary              D  Removing 1 heap dumps
2025-02-20 14:55:52.804  5552-5603  xxx.xxx.xxx             I  hprof: heap dump "/storage/emulated/0/Download/leakcanary-xxx.xxx.xxx/2025-02-20_14-55-52_797.hprof" starting...
2025-02-20 14:55:56.541  5552-5603  xxx.xxx.xxx             I  hprof: heap dump completed (43MB) in 3.736s objects 639364 objects with stack traces 0
2025-02-20 14:55:56.758  5552-5603  LeakCanary              D  Enqueuing heap analysis for /storage/emulated/0/Download/leakcanary-xxx.xxx.xxx/2025-02-20_14-55-52_797.hprof on WorkManager remote worker
2025-02-20 14:55:56.844  5552-6733  LeakCanary              D  Analysis in progress, 0% done, working on Parsing heap dump
2025-02-20 14:55:57.687  5552-5563  xxx.xxx.xxx             I  Background concurrent mark compact GC freed 65892(1640KB) AllocSpace objects, 7(572KB) LOS objects, 50% free, 17MB/35MB, paused 12.694ms,2.686ms total 59.810ms
2025-02-20 14:55:58.087  5552-5563  xxx.xxx.xxx             I  Background concurrent mark compact GC freed 140465(3552KB) AllocSpace objects, 5(2004KB) LOS objects, 42% free, 32MB/56MB, paused 538us,2.731ms total 112.078ms
2025-02-20 14:55:59.592  5552-5563  xxx.xxx.xxx             I  Background concurrent mark compact GC freed 1163128(27MB) AllocSpace objects, 0(0B) LOS objects, 41% free, 33MB/57MB, paused 493us,2.865ms total 107.471ms
2025-02-20 14:56:00.119  5552-5563  xxx.xxx.xxx             I  Background concurrent mark compact GC freed 1245194(28MB) AllocSpace objects, 0(0B) LOS objects, 41% free, 33MB/57MB, paused 692us,3.531ms total 131.905ms
2025-02-20 14:56:44.639  5552-5602  WM-WorkerWrapper	I  Work [ id=708520d7-47ee-4d96-af62-4df81bec08b6, tags={ info.mqtt.android.service.ping.PingWorker } ] was cancelled (Ask Gemini)
                                                                               java.util.concurrent.CancellationException: Task was cancelled.
                                                                               at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1183)
                                                                               at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:513)
                                                                               at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
                                                                               at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
                                                                               at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                               at java.lang.Thread.run(Thread.java:1012)

**Comment by hannesa2** [comment]
First please use most recent version.
If a job is canceled doesn't mean point to a malfunction. Does the system still receives messages is the important question.
If you really want to get rid of workmanager, you should use battery draining version 3.x

**Comment by chlim77** [comment]
I tried using version 4.3, but I have the same issue.
I think the problem is not that WorkManager is canceled, but that GC operation does not stop.
Even if it is not necessarily a situation where it runs in sleep mode for tens of hours, if you do a task that consumes a lot of memory while downloading a file, GC operates, and GC does not stop even after the tasks are finished. When I did the same test with version 3.6.6, GC operates, but when the tasks are finished, GC operation also ends.
I want to use version 4.x from a battery perspective. Is there a way?

**Comment by hannesa2** [comment]
I'm not sure, if my advice is right, but I would invest time to avoid the GC. Why it's that painful on your side ?

**Comment by wwqbus** [comment]
maybe we can catch the error and log it more friendly way so people arent confused with it?

**Comment by hannesa2** [comment]
Which one do you want to try catch ?
The `CancellationException` will not work.

**Comment by wwqbus** [comment]
ah correct i need to read in a bit more around the workers

**Comment by SM2A** [comment]
Hi
I have done so much research and do many trial and error on different MQTT android clients even the original paho and hiveMQ.
The problem is no mather how we try do make it work, Android system won't let app to send ping requests.

**Comment by minhdangoz** [comment]
This is solution

``` kt
internal class AlarmPingSender(
    val service: MqttService,
    val id: String,
    private val pingLogging: Boolean = false,
    private val keepPingRecords: Int = 1000
) : MqttPingSender {

    private val workManager = WorkManager.getInstance(service)

    override fun init(comms: ClientComms) {
        clientCommsMap[id] = comms
        messageDatabase = service.messageDatabase
        Timber.w("--> AlarmPingSender Init ping job $id")
    }

    override fun start() {
        Timber.d("--> AlarmPingSender Start ping job $id")
        clientCommsMap[id]?.clientState?.let {
            schedule(clientCommsMap[id]!!.keepAlive)
        } ?: Timber.e("FIXME: try to start ping schedule, but clientState null, not able to get keepAlive")
    }

    override fun stop() {
        //remove the clientComms from the map
        Timber.d("--> AlarmPingSenderStop ping job $id")
        workManager.cancelUniqueWork("${PING_JOB}_$id")
    }

    override fun schedule(delayInMilliseconds: Long) {
        Timber.d("$id: Schedule next alarm at ${sdf.format(Date(System.currentTimeMillis() + delayInMilliseconds))}")

        // Check if work is already scheduled with this ID
        val workInfo = workManager.getWorkInfosForUniqueWork("${PING_JOB}_$id").get()

        // Only schedule if no work exists or all existing work is finished/cancelled
        if (workInfo.isEmpty() || workInfo.all { it.state.isFinished }) {
            val pingWork = OneTimeWorkRequest.Builder(PingWorker::class.java)
            val data = Data.Builder()
            data.putBoolean("logging", pingLogging)
            data.putInt("keepRecordCount", keepPingRecords)
            data.putString("id", id)

            pingWork
                .setInitialDelay(30, TimeUnit.SECONDS)
                .setInputData(data.build())

            workManager.enqueueUniqueWork(
                "${PING_JOB}_$id",
                ExistingWorkPolicy.REPLACE,
                pingWork.build()
            )

            Timber.d("$id: Successfully scheduled new ping job")
        } else {
            Timber.w("$id: I GOT YOU Ping job already scheduled, skipping")
        }
    }

    companion object {
        internal var clientCommsMap: ConcurrentHashMap<String, ClientComms> = ConcurrentHashMap()

        private const val PING_JOB = "PING_JOB"

        internal var messageDatabase: MqMessageDatabase? = null

        @SuppressLint("ConstantLocale")
        internal val sdf = SimpleDateFormat("yyyy-MM-dd HH:mm:ss'Z'", Locale.getDefault())
    }

}

```

**Comment by hannesa2** [comment]
@minhdangoz 
Thanks a lot, may I ask why you use 30 seconds and not the given delay ?

<img width="724" alt="Image" src="https://github.com/user-attachments/assets/fe04e55e-6f0c-44bf-8961-f6f1bbd5acfc" />

**Comment by minhdangoz** [comment]
void schedule(long delayInMilliseconds);

delay from MqttPingSender is about 100ms which cause WorkManager keep killing the PingWorker (ExistingWorkPolicy.REPLACE). That's reason why I put 30 seconds instead (for my use case).
