### ISSUE TITLE
The foreground service types are required since Android 14

### ISSUE THREAD

**Issue by sirambd** [hannesa2/paho.mqtt.android#556]
`The latest version 4.2` does not work for Android 14 and above.
And the reason is due to the fact that since android 14, when you use a foreground service you have to specify the `foregroundServiceType`.

https://developer.android.com/about/versions/14/changes/fgs-types-required

```
android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{c17b940 17461:com.infomaniak.drive/u0a169} targetSDK=34 has been prohibited
at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:53)
at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:49)
at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
at android.os.Parcel.readParcelable(Parcel.java:4852)
at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
at android.os.Parcel.createException(Parcel.java:3041)
at android.os.Parcel.readException(Parcel.java:3024)
at android.os.Parcel.readException(Parcel.java:2966)
at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
at android.app.Service.startForeground(Service.java:862)
at androidx.work.impl.foreground.SystemForegroundService$Api31Impl.startForeground(SystemForegroundService.java:193)
at androidx.work.impl.foreground.SystemForegroundService$1.run(SystemForegroundService.java:129)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by hannesa2** [comment]
But with versions >= `4.x` you don't need a foreground service anymore. That's the breaking change of `4.0`
https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.0
this is the pull request
https://github.com/hannesa2/paho.mqtt.android/pull/430

**Comment by hannesa2** [comment]
In the meantime I close it, but if you have still the issue, please reopen it again
