### ISSUE TITLE
Calling disconnect twice results in crash

### ISSUE THREAD

**Issue by fabmazz** [hannesa2/paho.mqtt.android#561]
I have a code that calls `client.disconnect()` when certain conditions are met.

However, I also want to disconnect when closing the fragment.

When I try to call `client.disconnect()` again, after the first one, the library crashes:
```
Process: it.reyboz.bustorino.debug, PID: 26148
java.lang.IllegalArgumentException: Invalid ClientHandle >wss://mapi.5t.torino.it:443/scre:mqtt-explorer-f173f581:it.reyboz.bustorino.debug<
at info.mqtt.android.service.MqttService.getConnection(MqttService.kt:492)
at info.mqtt.android.service.MqttService.disconnect(MqttService.kt:332)
at info.mqtt.android.service.MqttAndroidClient.disconnect(MqttAndroidClient.kt:284)
```

**Comment by hannesa2** [comment]
#563
