### ISSUE TITLE
Network change results in a NullPointerException.

### ISSUE THREAD

**Issue by 973496491** [hannesa2/paho.mqtt.android#569]
When using the library (version 4.2.1), I encountered the following exception. Currently, I can confirm that it occurs when there is a change in the network. This has left me quite puzzled. Please help me.

```
Key .exception expected Parcelable but value was a org.eclipse.paho.client.mqttv3.MqttException.  The default value <null> was returned.
java.lang.ClassCastException: org.eclipse.paho.client.mqttv3.MqttException cannot be cast to android.os.Parcelable
                            	at android.os.Bundle.getParcelable(Bundle.java:1008)
                            	at info.mqtt.android.service.MqttAndroidClient.connectionLostAction(MqttAndroidClient.kt:1309)
                            	at info.mqtt.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.kt:910)
                            	at info.mqtt.android.service.MqttAndroidClient.access$onReceive(MqttAndroidClient.kt:46)
                            	at info.mqtt.android.service.MqttAndroidClient$collect$1$1.invoke(MqttAndroidClient.kt:250)
                            	at info.mqtt.android.service.MqttAndroidClient$collect$1$1.invoke(MqttAndroidClient.kt:250)
                            	at info.mqtt.android.service.MqttService.collect$suspendConversion0(MqttService.kt:270)
                            	at info.mqtt.android.service.MqttService.access$collect$suspendConversion0(MqttService.kt:180)
                            	at info.mqtt.android.service.MqttService$collect$2.emit(MqttService.kt:270)
                            	at info.mqtt.android.service.MqttService$collect$2.emit(MqttService.kt:270)
                            	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:392)
                            	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
                            	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                            	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                            	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                            	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                            	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
                            	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
                            	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
                            	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
```

```
java.lang.NullPointerException: Parameter specified as non-null is null: method com.a.b.module.MqttManager$connect$1.connectionLost, parameter cause
                            	at com.a.b.module.MqttManager$connect$1.connectionLost(Unknown Source:2)
                            	at info.mqtt.android.service.MqttAndroidClient.connectionLostAction(MqttAndroidClient.kt:980)
                            	at info.mqtt.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.kt:910)
                            	at info.mqtt.android.service.MqttAndroidClient.access$onReceive(MqttAndroidClient.kt:46)
                            	at info.mqtt.android.service.MqttAndroidClient$collect$1$1.invoke(MqttAndroidClient.kt:250)
                            	at info.mqtt.android.service.MqttAndroidClient$collect$1$1.invoke(MqttAndroidClient.kt:250)
                            	at info.mqtt.android.service.MqttService.collect$suspendConversion0(MqttService.kt:270)
                            	at info.mqtt.android.service.MqttService.access$collect$suspendConversion0(MqttService.kt:180)
                            	at info.mqtt.android.service.MqttService$collect$2.emit(MqttService.kt:270)
                            	at info.mqtt.android.service.MqttService$collect$2.emit(MqttService.kt:270)
                            	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:392)
                            	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
                            	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                            	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                            	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                            	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                            	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
                            	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
                            	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
                            	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
```

**Comment by ljLJ402** [comment]
paho.client.mqttv3.MqttException cannot be cast to android.os.Parcelable

**Comment by hannesa2** [comment]
One suspect is https://github.com/hannesa2/paho.mqtt.android/pull/527
Does it happen on 4.2.0 as well ?

**Comment by hannesa2** [comment]
> The version I used is 4.2.1

I know, but does it happen on 4.2.0 as well ?

**Comment by hannesa2** [comment]
I guess this solves it https://github.com/hannesa2/paho.mqtt.android/pull/570

**Comment by ljLJ402** [comment]
> > The version I used is 4.2.1
> 
> I know, but does it happen on 4.2.0 as well ?

C
![Uploading d5a7e333-5927-40f7-bb51-a2c262a4bc55.jpeg…]()
ould not find com.github.hannesa2:paho.mqtt.android:4.2.0.

**Comment by hannesa2** [comment]
https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.2.2 
Please reopen if it still exists.

**Comment by ljLJ402** [comment]
> https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.2.2 Please reopen if it still exists.

![0b2091f2-cff0-4666-bde9-844690820ee4](https://github.com/hannesa2/paho.mqtt.android/assets/39945684/80652fa6-7d55-4428-bc0d-111c6d59fb70)

    implementation 'com.github.hannesa2:paho.mqtt.android:4.2.2'
 when lost network ,ANR again

**Comment by hannesa2** [comment]
I can solve it, when you help me to figure out, what's wrong here

**Comment by ljLJ402** [comment]
> I can solve it, when you help me to figure out, what's wrong here

It is  running ok ,but when  I close the network, app anr happened

**Comment by 973496491** [comment]
I attempted to update to version 4.2.2, but the issue still persists. When I lose network connection, the application throws an exception, leading to a crash.

**Comment by 973496491** [comment]
> > https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.2.2如果仍然存在，请重新打开。
> 
> ![0b2091f2-cff0-4666-bde9-844690820ee4](https://private-user-images.githubusercontent.com/39945684/306997943-80652fa6-7d55-4428-bc0d-111c6d59fb70.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTM4NTMsIm5iZiI6MTcwODY1MzU1MywicGF0aCI6Ii8zOTk0NTY4NC8zMDY5OTc5NDMtODA2NTJmYTYtN2Q1NS00NDI4LWJjMGQtMTExYzZkNTlmYjcwLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwMTU5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjlkNWE1MjM2MmQ5YmU2MjMxMTk5Njk3YWI1YjgyZDBmOGQ2OGQxMTM1ZWRhZjM1NTc1ZTRmMWU1NDFlNGQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YNQwmwZTJiQoyaELLzic1lTNqmEmmiJXa1uxaq2LQ_8)
> 
> ```
> implementation 'com.github.hannesa2:paho.mqtt.android:4.2.2'
> ```
> 
> 掉网时再次ANR

我尝试更新到版本 4.2.2，但问题仍然存在。当我失去网络连接时，应用程序会抛出异常，导致崩溃。

**Comment by 973496491** [comment]
> https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.2.2 Please reopen if it still exists.


I attempted to update to version 4.2.2, but the issue still persists. When I lose network connection, the application throws an exception, leading to a crash.

**Comment by ljLJ402** [comment]
> I guess I found the root cause https://github.com/hannesa2/paho.mqtt.android/pull/527/files#r1500260389
> 
> Please give it a try https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.2.3

I have tried 4.2.3,It is ok when I make the network offline.

**Comment by 973496491** [comment]
> I guess I found the root cause https://github.com/hannesa2/paho.mqtt.android/pull/527/files#r1500260389
> 
> Please give it a try https://github.com/hannesa2/paho.mqtt.android/releases/tag/4.2.3


After updating to version 4.2.3, the offline network application no longer crashes. It seems that this issue has been fixed.

**Comment by 973496491** [comment]
> paho.client.mqttv3.MqttException cannot be cast to android.os.Parcelable
> 
> 同样碰到了这个问题 gradle 8.6 AGP 8.2.2

你在断网之后, MQTT自动断开, 然后打开网络重新连接MQTT的时候, 会出现订阅主题失败的情况吗? 具体表现为MQTT先是连接成功, 然后断开连接.

**Comment by 973496491** [comment]
> paho.client.mqttv3.MqttException cannot be cast to android.os.Parcelable
> 
> 同样碰到了这个问题 gradle 8.6 AGP 8.2.2

哈喽, 你那边有没有出现这个问题, MQTT断网被强制断开之后重新创建连接, 出现连接成功之后自动断开的问题.
```
Bundle[{.exceptionStack=已断开连接 (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:270)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more
, .errorMessage=已断开连接, .exception=已断开连接 (32109) - java.io.EOFException, .callbackAction=onConnectionLost, .clientHandle=tcp://<host>:<port>:pmswAaSQoC1iDiOkri9T:com.aa.bb, .callbackStatus=OK}]
```

**Comment by ljLJ402** [comment]
> > paho.client.mqttv3.MqttException cannot be cast to android.os.Parcelable
> > 同样碰到了这个问题 gradle 8.6 AGP 8.2.2
> 
> 哈喽, 你那边有没有出现这个问题, MQTT断网被强制断开之后重新创建连接, 出现连接成功之后自动断开的问题.
> 
> ```
> Bundle[{.exceptionStack=已断开连接 (32109) - java.io.EOFException
> 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
> 	at java.lang.Thread.run(Thread.java:920)
> Caused by: java.io.EOFException
> 	at java.io.DataInputStream.readByte(DataInputStream.java:270)
> 	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
> 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
> 	... 1 more
> , .errorMessage=已断开连接, .exception=已断开连接 (32109) - java.io.EOFException, .callbackAction=onConnectionLost, .clientHandle=tcp://<host>:<port>:pmswAaSQoC1iDiOkri9T:com.aa.bb, .callbackStatus=OK}]
> ```

适用4.2.3版本之后断网不会发生ANR了，我这边没有出现你说的这种崩溃，我在断网后添加了重连（下图），保证网络恢复时mqtt的同步恢复。
![63c3cf86-be9c-4fea-9c28-3a9868fec31f](https://github.com/hannesa2/paho.mqtt.android/assets/39945684/841b0803-77e6-415c-8be9-5a8acdc1677f)

**Comment by ljLJ402** [comment]
> EOFException



> > paho.client.mqttv3.MqttException cannot be cast to android.os.Parcelable
> > 同样碰到了这个问题 gradle 8.6 AGP 8.2.2
> 
> 哈喽, 你那边有没有出现这个问题, MQTT断网被强制断开之后重新创建连接, 出现连接成功之后自动断开的问题.
> 
> ```
> Bundle[{.exceptionStack=已断开连接 (32109) - java.io.EOFException
> 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
> 	at java.lang.Thread.run(Thread.java:920)
> Caused by: java.io.EOFException
> 	at java.io.DataInputStream.readByte(DataInputStream.java:270)
> 	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
> 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
> 	... 1 more
> , .errorMessage=已断开连接, .exception=已断开连接 (32109) - java.io.EOFException, .callbackAction=onConnectionLost, .clientHandle=tcp://<host>:<port>:pmswAaSQoC1iDiOkri9T:com.aa.bb, .callbackStatus=OK}]
> ```

这个问题应该是文件流读取时出现的，read的返回结果为-1时说明当前的io流里已经没有数据了，不要再继续读取了，等待mqtt客户端再次接收到值再读取。

**Comment by 973496491** [comment]
> > EOFException
> 
> > > paho.client.mqttv3.MqttException cannot be cast to android.os.Parcelable
> > > 同样碰到了这个问题 gradle 8.6 AGP 8.2.2
> > 
> > 
> > 哈喽, 你那边有没有出现这个问题, MQTT断网被强制断开之后重新创建连接, 出现连接成功之后自动断开的问题.
> > ```
> > Bundle[{.exceptionStack=已断开连接 (32109) - java.io.EOFException
> > 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
> > 	at java.lang.Thread.run(Thread.java:920)
> > Caused by: java.io.EOFException
> > 	at java.io.DataInputStream.readByte(DataInputStream.java:270)
> > 	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
> > 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
> > 	... 1 more
> > , .errorMessage=已断开连接, .exception=已断开连接 (32109) - java.io.EOFException, .callbackAction=onConnectionLost, .clientHandle=tcp://<host>:<port>:pmswAaSQoC1iDiOkri9T:com.aa.bb, .callbackStatus=OK}]
> > ```
> 
> 这个问题应该是文件流读取时出现的，read的返回结果为-1时说明当前的io流里已经没有数据了，不要再继续读取了，等待mqtt客户端再次接收到值再读取。

咱们能添加一下好友私聊请教一下吗, 就不要在已关闭的帖子下面继续了?  如果不方便就算啦

**Comment by ljLJ402** [comment]
> > > EOFException
> > 
> > 
> > > > paho.client.mqttv3.MqttException cannot be cast to android.os.Parcelable
> > > > 同样碰到了这个问题 gradle 8.6 AGP 8.2.2
> > > 
> > > 
> > > 哈喽, 你那边有没有出现这个问题, MQTT断网被强制断开之后重新创建连接, 出现连接成功之后自动断开的问题.
> > > ```
> > > Bundle[{.exceptionStack=已断开连接 (32109) - java.io.EOFException
> > > 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
> > > 	at java.lang.Thread.run(Thread.java:920)
> > > Caused by: java.io.EOFException
> > > 	at java.io.DataInputStream.readByte(DataInputStream.java:270)
> > > 	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
> > > 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
> > > 	... 1 more
> > > , .errorMessage=已断开连接, .exception=已断开连接 (32109) - java.io.EOFException, .callbackAction=onConnectionLost, .clientHandle=tcp://<host>:<port>:pmswAaSQoC1iDiOkri9T:com.aa.bb, .callbackStatus=OK}]
> > > ```
> > 
> > 
> > 这个问题应该是文件流读取时出现的，read的返回结果为-1时说明当前的io流里已经没有数据了，不要再继续读取了，等待mqtt客户端再次接收到值再读取。
> 
> 咱们能添加一下好友私聊请教一下吗, 就不要在已关闭的帖子下面继续了? 如果不方便就算啦

可以，怎么联系？

**Comment by 973496491** [comment]
> > > > EOFException
> > > 
> > > 
> > > > > paho.client.mqttv3.MqttException cannot be cast to android.os.Parcelable
> > > > > 同样碰到了这个问题 gradle 8.6 AGP 8.2.2
> > > > 
> > > > 
> > > > 哈喽, 你那边有没有出现这个问题, MQTT断网被强制断开之后重新创建连接, 出现连接成功之后自动断开的问题.
> > > > ```
> > > > Bundle[{.exceptionStack=已断开连接 (32109) - java.io.EOFException
> > > > 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
> > > > 	at java.lang.Thread.run(Thread.java:920)
> > > > Caused by: java.io.EOFException
> > > > 	at java.io.DataInputStream.readByte(DataInputStream.java:270)
> > > > 	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
> > > > 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
> > > > 	... 1 more
> > > > , .errorMessage=已断开连接, .exception=已断开连接 (32109) - java.io.EOFException, .callbackAction=onConnectionLost, .clientHandle=tcp://<host>:<port>:pmswAaSQoC1iDiOkri9T:com.aa.bb, .callbackStatus=OK}]
> > > > ```
> > > 
> > > 
> > > 这个问题应该是文件流读取时出现的，read的返回结果为-1时说明当前的io流里已经没有数据了，不要再继续读取了，等待mqtt客户端再次接收到值再读取。
> > 
> > 
> > 咱们能添加一下好友私聊请教一下吗, 就不要在已关闭的帖子下面继续了? 如果不方便就算啦
> 
> 可以，怎么联系？

cxyuejian   这是我的微信    咱们加一下?
