### ISSUE TITLE
Sending when not connected results in  crash

### ISSUE THREAD

**Issue by FJEagle** [hannesa2/paho.mqtt.android#572]
When my app comes to foreground after being in background for a while, the app will crash with following trace:

`
2-23 11:51:23>e:CrashHandler,42,trace:java.lang.Throwable: not connected
	at info.mqtt.android.service.MqttAndroidClient.simpleAction(MqttAndroidClient.kt:1008)
	at info.mqtt.android.service.MqttAndroidClient.sendAction(MqttAndroidClient.kt:1030)
	at info.mqtt.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.kt:904)
	at info.mqtt.android.service.MqttAndroidClient.access$onReceive(MqttAndroidClient.kt:44)
	at info.mqtt.android.service.MqttAndroidClient$collect$1$1.invoke(MqttAndroidClient.kt:248)
	at info.mqtt.android.service.MqttAndroidClient$collect$1$1.invoke(MqttAndroidClient.kt:248)
	at info.mqtt.android.service.MqttService.collect$suspendConversion0(MqttService.kt:268)
	at info.mqtt.android.service.MqttService.access$collect$suspendConversion0(MqttService.kt:180)
	at info.mqtt.android.service.MqttService$collect$2.emit(MqttService.kt:268)
	at info.mqtt.android.service.MqttService$collect$2.emit(MqttService.kt:268)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:382)
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ea94c1e, Dispatchers.Default]
`

As shown in trace, the exception is not triggered by businesss logic directly. Guess it is impossible to catch this exception in business logic.

lib ver: 4.2 ( 4.2.2 same)

**Comment by FJEagle** [comment]
Probably caused by  MqttTokenAndroid.waitForCompletion. The trace belongs to the pendingException, so the exception can be caught.
