### ISSUE TITLE
connectionLostAction crash: MqttException cannot be cast to android.os.Parcelable

### ISSUE THREAD

**Issue by FJEagle** [hannesa2/paho.mqtt.android#575]
Crash log:
`2-24 10:56:55>e:CrashHandler,40,cause:ClassCastException: org.eclipse.paho.client.mqttv3.MqttException cannot be cast to android.os.Parcelable
2-24 10:56:55>e:CrashHandler,42,trace:java.lang.ClassCastException: org.eclipse.paho.client.mqttv3.MqttException cannot be cast to android.os.Parcelable
	at info.mqtt.android.service.MqttAndroidClient.connectionLostAction(MqttAndroidClient.kt:1308)
	at info.mqtt.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.kt:910)
	at info.mqtt.android.service.MqttAndroidClient.access$onReceive(MqttAndroidClient.kt:46)
	at info.mqtt.android.service.MqttAndroidClient$collect$1$1.invoke(MqttAndroidClient.kt:250)
	at info.mqtt.android.service.MqttAndroidClient$collect$1$1.invoke(MqttAndroidClient.kt:250)
	at info.mqtt.android.service.MqttService.collect$suspendConversion0(MqttService.kt:270)
	at info.mqtt.android.service.MqttService.access$collect$suspendConversion0(MqttService.kt:180)
	at info.mqtt.android.service.MqttService$collect$2.emit(MqttService.kt:270)
	at info.mqtt.android.service.MqttService$collect$2.emit(MqttService.kt:270)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:392)
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@511bd39, Dispatchers.IO]`

lib ver: 4.2.2

**Comment by 973496491** [comment]
Please update to version 4.2.3. In my opinion, it has already been fixed. You can track this issue. #569
