### ISSUE TITLE
BroadcastReceiver components are not allowed to bind to services

### ISSUE THREAD

**Issue by UnumInAgro** [hannesa2/paho.mqtt.android#599]
android.content.ReceiverCallNotAllowedException: BroadcastReceiver components are not allowed to bind to services
                                                                                                    	at android.app.ReceiverRestrictedContext.bindService(ContextImpl.java:124)
                                                                                                    	at info.mqtt.android.service.MqttAndroidClient.connect(MqttAndroidClient.kt:221)

**Comment by hannesa2** [comment]
The first suspect is that it's related to your code. Please show me a running sample

**Comment by UnumInAgro** [comment]
Yes, this is related to my code. The situation is this: I start Broadcast on an alarm clock, it tries to start connect mqtt. This happens in the background after the device is rebooted. There are possible solutions to the problem, but this needs to be done in your library. https://stackoverflow.com/questions/29114072/broadcastreceiver-components-are-not-allowed-to-bind-to-services-in-android

**Comment by UnumInAgro** [comment]
need use context.applicationContext unstead context from broadcast
