### ISSUE TITLE
MQTT连接后androidx.work mqtt的消息也收不到

### ISSUE THREAD

**Issue by pichsy** [hannesa2/paho.mqtt.android#664]
I  Work [ id=8d3a8164-0e0c-4082-a9cc-02960adc14df, tags={ info.mqtt.android.service.ping.PingWorker } ] was cancelled
                                                                                                    java.util.concurrent.CancellationException: Task was cancelled.
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1183)
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:513)
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
                                                                                                    	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
                                                                                                    	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:929)

**Comment by hannesa2** [comment]
> Task was cancelled.

**Comment by mayurappscripde** [comment]
Im getting same issue in Android 14 (API level 34) only

**Comment by hannesa2** [comment]
@mayurappscripde  @pichsy 
https://github.com/hannesa2/paho.mqtt.android/issues/502#issuecomment-2288651148
