### ISSUE TITLE
Options method setUsername does not work correctly

### ISSUE THREAD

**Issue by matteopaolucci** [hannesa2/paho.mqtt.android#733]
I'm trying to connect to a self-hosted MQTT broker (mosquitto) with TLS and the methods *setUsername* and *setPasswords* are not working correctly. I am saying this because the mosquitto “logs” are different depending on the device used. I had to **enable** the *allow_anonymous* option inside the *mosquitto.conf* file to make it work, otherwise you  get the exception: 
```
java.lang.RuntimeException: Not authorized to connect (5)
    at com.matteopaolucci.elettrotp.ui.home.HomeFragment$2.onFailure(HomeFragment.java:288)
    at info.mqtt.android.service.MqttTokenAndroid.notifyFailure(MqttTokenAndroid.kt:66)
    at info.mqtt.android.service.MqttAndroidClient.simpleAction(MqttAndroidClient.kt:1018)
    at info.mqtt.android.service.MqttAndroidClient.connectAction(MqttAndroidClient.kt:957)
    at info.mqtt.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.kt:896)
    at info.mqtt.android.service.MqttAndroidClient.access$onReceive(MqttAndroidClient.kt:46)
    at info.mqtt.android.service.MqttAndroidClient$collect$1$1.invoke(MqttAndroidClient.kt:250)
    at info.mqtt.android.service.MqttAndroidClient$collect$1$1.invoke(MqttAndroidClient.kt:250)
    at info.mqtt.android.service.MqttService.collect$suspendConversion0(MqttService.kt:271)
    at info.mqtt.android.service.MqttService.access$collect$suspendConversion0(MqttService.kt:181)
    at info.mqtt.android.service.MqttService$collect$2.emit(MqttService.kt:271)
    at info.mqtt.android.service.MqttService$collect$2.emit(MqttService.kt:271)
    at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:392)
    at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
    Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b19d523, Dispatchers.IO]
    Caused by: Not authorized to connect (5)
    at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28)
    at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:1053)
    at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:151)
    at java.lang.Thread.run(Thread.java:923)
```

Java Code:
```java

public class HomeFragment extends Fragment implements MqttCallbackExtended {
    private MqttAndroidClient mqttClient;
    private MqttConnectOptions mqttOptions;
    private TextView textViewSogliaAttuale;
    private TextView textViewPressione;
    private Button btnInviaSoglia;
    private Switch switchModUnaChiusura;
    private NumberPicker numberPickerUnita;
    private NumberPicker numberPickerDecimali;
    private int defaultTextColor;
    private boolean isSubscribed;

    private boolean isSwitchActivatedByMessage;
    private FragmentHomeBinding binding;

    public View onCreateView(@NonNull LayoutInflater inflater,
                             ViewGroup container, Bundle savedInstanceState) {
        binding = FragmentHomeBinding.inflate(inflater, container, false);
        View root = binding.getRoot();

        textViewSogliaAttuale = binding.textViewSogliaAttuale;
        textViewPressione = binding.textViewPressione;
        btnInviaSoglia = binding.btnNuovaSoglia;
        switchModUnaChiusura = binding.switchModUnaChiusura;
        numberPickerUnita = binding.numberPickerU;
        numberPickerDecimali = binding.numberPickerD;
        numberPickerUnita.setMinValue(12);
        numberPickerUnita.setMaxValue(13);
        numberPickerUnita.setEnabled(false);
        numberPickerDecimali.setMinValue(0);
        numberPickerDecimali.setMaxValue(99);
        numberPickerDecimali.setEnabled(false);
        defaultTextColor = textViewSogliaAttuale.getCurrentTextColor();
        isSwitchActivatedByMessage = true;
        isSubscribed = false;

        switchModUnaChiusura.setOnCheckedChangeListener((mySwitch, isChecked) -> {
            String message;
            if (isChecked) {
                message = "<message>";
            } else {
                message = "<other-message>";
            }
            if (!isSwitchActivatedByMessage) {
                mqttClient.publish(getString(R.string.publish_topic), new MqttMessage(message.getBytes()));

                mySwitch.setEnabled(false);
            }
        });
        btnInviaSoglia.setOnClickListener(v -> {
            try {
                setSoglia(v);
            } catch (MqttException e) {
                throw new RuntimeException(e);
            }
        });

        mqttOptions = new MqttConnectOptions();
        mqttOptions.setAutomaticReconnect(true);
        mqttOptions.setKeepAliveInterval(300);
        mqttOptions.setUserName("<username>");
        mqttOptions.setPassword("<password>".toCharArray());
        mqttClient = new MqttAndroidClient(root.getContext(), getString(R.string.server_uri), "android-" + Build.MODEL);
        mqttClient.setCallback(this);
        try {
            mqttOptions.setSocketFactory(mqttClient.getSSLSocketFactory(getResources().openRawResource(R.raw.clientcert), getString(R.string.keystore_password)));
        } catch (MqttSecurityException e) {
            throw new RuntimeException(e);
        }

        return root;
    }

    @Override
    public void onResume() {
        super.onResume();
        if (!mqttClient.isConnected()) {
            try {
                connectToMqttBroker();
            } catch (MqttException e) {
                throw new RuntimeException(e);
            }
        } else {
            if (switchModUnaChiusura.isEnabled()) {
                switchModUnaChiusura.setEnabled(false);
            }
            if (btnInviaSoglia.isEnabled()) {
                btnInviaSoglia.setEnabled(false);
                numberPickerDecimali.setEnabled(false);
                numberPickerUnita.setEnabled(false);
            }
            if (!isSubscribed) {
                subscribeToTopic();
            }
        }
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        binding = null;
    }

    @Override
    public void connectComplete(boolean reconnect, String serverURI) {
           /* not related code */
        }
    }

    @Override
    public void connectionLost(Throwable cause) {
    }

    @Override
    public void messageArrived(String topic, MqttMessage message) {
       /* not related code */
    }

    @Override
    public void deliveryComplete(IMqttDeliveryToken token) {
       /* not related code */
    }

    private void connectToMqttBroker() throws MqttException {
        mqttClient.connect(mqttOptions, new IMqttActionListener() {
            @Override
            public void onSuccess(IMqttToken asyncActionToken) {
                if (isAdded()) {
                    subscribeToTopic();
                } else {
                    isSubscribed = false;
                }
            }

            @Override
            public void onFailure(IMqttToken asyncActionToken, Throwable exception) {
                throw new RuntimeException(exception);
            }
        });
    }

    private void subscribeToTopic() {
       /* not related code */
}
```

mosquitto.conf working:
```
per_listener_settings true
listener 8883 0.0.0.0
allow_anonymous true
connection_messages true

#SSL
cafile /mosquitto/config/certs/fullchain1.pem
certfile /mosquitto/config/certs/cert1.pem
keyfile /mosquitto/config/certs/privkey1.pem

#ACL
acl_file /mosquitto/config/acl_file

#Access Control
password_file /mosquitto/config/password_file

#LOGS
log_dest file /mosquitto/log/mosquitto.log
log_type all
```

mosquitto.conf **NOT** working:
```
per_listener_settings true
listener 8883 0.0.0.0
allow_anonymous false    <----
connection_messages true

#SSL
cafile /mosquitto/config/certs/fullchain1.pem
certfile /mosquitto/config/certs/cert1.pem
keyfile /mosquitto/config/certs/privkey1.pem

#ACL
acl_file /mosquitto/config/acl_file

#Access Control
password_file /mosquitto/config/password_file

#LOGS
log_dest file /mosquitto/log/mosquitto.log
log_type all
```

**Note the difference in the end of the second line in both cases**

mosquitto.log when connecting from **android**:
```
1733827338: New connection from <android-ip>:58152 on port 8883.
1733827339: New client connected from <android-ip>:58152 as android-<model> (p2, c1, k60).
1733827339: No will message specified.
1733827339: Sending CONNACK to android-<model> (0, 0)
1733827339: Received SUBSCRIBE from android-<model>
1733827339:     <topic> (QoS 1)
1733827339: android-<model> 1 <topic>
1733827339: Sending SUBACK to android-<model>
1733827399: Received PINGREQ from android-<model>
...
```

mosquitto.log when connecting from **PC** (not in the same PC of the broker):
```
1733780729: New connection from <pc-ip>:36930 on port 8883.                                                                                    
1733780730: New client connected from <pc-ip>:36930 as auto-3742172C-1183-649F-E4B6-4A6C49607646 (p2, c1, k60, u'<username>').                    
1733780730: No will message specified.                                                                                                            
1733780730: Sending CONNACK to auto-3742172C-1183-649F-E4B6-4A6C49607646 (0, 0)                                                                   
1733780730: Received SUBSCRIBE from auto-3742172C-1183-649F-E4B6-4A6C49607646                                                                     
1733780730:      <topic> (QoS 0)                                                                                                       
1733780730: auto-3742172C-1183-649F-E4B6-4A6C49607646 0  <topic>
...
```

P.S. sensible information is substituted with `<sensible-info>`

**Comment by matteopaolucci** [comment]
My bad, i was using a wrong method  `mqttClient.connect(mqttOptions, new IMqttActionListener() {<code>})` instead of `mqttClient.connect(mqttOptions, null, new IMqttActionListener() {<code>})`
